-- ============================================================
-- B2B Growth Funnel Analytics - Trend & Cohort Analysis
-- ============================================================
-- Purpose: Time-series and cohort-based analysis to understand
--          growth trends, performance changes, and channel evolution
-- 
-- Questions answered:
--   Q1. Monthly acquisition performance trends
--   Q2. Month-over-month growth rates
--   Q3. Cumulative spend and revenue
--   Q4. Acquisition cohort conversion performance
--   Q5. Cohort conversion by channel
--   Q6. Monthly channel revenue rankings
--   Q7. Conversion trends with rolling average
-- ============================================================

USE growth_analytics;


-- ============================================================
-- Q1. Monthly Acquisition Performance
-- ============================================================
-- Complete monthly metrics from the pre-aggregated view
-- Shows volume, financial, and efficiency trends over time
-- ============================================================

SELECT 
    *
FROM 
    vw_monthly_acquisition_performance
ORDER BY 
    acquisition_month;


-- ============================================================
-- Q2. Month-over-Month Lead and Revenue Growth
-- ============================================================
-- Calculates growth rates between consecutive months
-- Useful for identifying acceleration or deceleration
-- ============================================================

WITH monthly AS (
    -- Get monthly totals
    SELECT 
        acquisition_month,
        leads,
        revenue
    FROM 
        vw_monthly_acquisition_performance
),
previous_month AS (
    -- Add previous month values using LAG window function
    SELECT 
        *,
        LAG(leads) OVER (ORDER BY acquisition_month)   AS previous_leads,
        LAG(revenue) OVER (ORDER BY acquisition_month) AS previous_revenue
    FROM 
        monthly
)
SELECT
    acquisition_month,
    
    -- Current and prior month values
    leads,
    previous_leads,
    
    -- Lead growth rate (%)
    ROUND(
        100.0 * (leads - previous_leads) / NULLIF(previous_leads, 0), 
        2
    ) AS lead_growth_pct,
    
    -- Revenue values
    revenue,
    previous_revenue,
    
    -- Revenue growth rate (%)
    ROUND(
        100.0 * (revenue - previous_revenue) / NULLIF(previous_revenue, 0), 
        2
    ) AS revenue_growth_pct
FROM 
    previous_month
ORDER BY 
    acquisition_month;


-- ============================================================
-- Q3. Cumulative Acquisition Spend and Revenue
-- ============================================================
-- Shows running totals of investment and returns
-- Useful for ROI analysis and break-even tracking
-- ============================================================

SELECT
    acquisition_month,
    acquisition_spend,
    revenue,
    
    -- Running total of all acquisition spend to date
    ROUND(
        SUM(acquisition_spend) OVER (
            ORDER BY acquisition_month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 
        2
    ) AS cumulative_spend,
    
    -- Running total of all revenue to date
    ROUND(
        SUM(revenue) OVER (
            ORDER BY acquisition_month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 
        2
    ) AS cumulative_revenue
FROM 
    vw_monthly_acquisition_performance
ORDER BY 
    acquisition_month;


-- ============================================================
-- Q4. Acquisition Cohort Conversion
-- ============================================================
-- Groups leads by the month they were acquired (cohort)
-- Shows how each cohort performs over their lifetime
-- ============================================================

SELECT
    DATE_FORMAT(acquisition_date, '%Y-%m') AS acquisition_cohort,
    
    -- Volume metrics per cohort
    COUNT(*)             AS leads,
    SUM(became_mql)      AS mqls,
    SUM(became_sql)      AS sqls,
    SUM(became_customer) AS customers,
    
    -- Cohort conversion rate
    ROUND(
        100.0 * SUM(became_customer) / NULLIF(COUNT(*), 0), 
        2
    ) AS cohort_conversion_rate_pct,
    
    -- Average velocity for successful conversions
    ROUND(
        AVG(CASE 
            WHEN became_customer = 1 
            THEN days_to_customer 
        END), 
        2
    ) AS avg_days_to_customer,
    
    -- Total revenue generated by cohort
    ROUND(SUM(revenue), 2) AS cohort_revenue
FROM 
    vw_lead_funnel_summary
GROUP BY 
    DATE_FORMAT(acquisition_date, '%Y-%m')
ORDER BY 
    acquisition_cohort;


-- ============================================================
-- Q5. Cohort Conversion by Channel
-- ============================================================
-- Analyzes how each channel's performance evolves over time
-- Compares channels within and across cohorts
-- ============================================================

SELECT
    DATE_FORMAT(acquisition_date, '%Y-%m') AS acquisition_cohort,
    channel,
    
    -- Volume metrics
    COUNT(*)             AS leads,
    SUM(became_customer) AS customers,
    
    -- Conversion rate
    ROUND(
        100.0 * SUM(became_customer) / NULLIF(COUNT(*), 0), 
        2
    ) AS conversion_rate_pct,
    
    -- Return on Ad Spend
    ROUND(
        SUM(revenue) / NULLIF(SUM(acquisition_cost), 0), 
        2
    ) AS roas
FROM 
    vw_lead_funnel_summary
GROUP BY 
    DATE_FORMAT(acquisition_date, '%Y-%m'), 
    channel
ORDER BY 
    acquisition_cohort, 
    roas DESC;


-- ============================================================
-- Q6. Monthly Channel Ranking by Revenue
-- ============================================================
-- Shows which channels are top performers each month
-- Useful for identifying shifts in channel effectiveness
-- ============================================================

WITH monthly_channel AS (
    -- Calculate metrics by month and channel
    SELECT
        DATE_FORMAT(acquisition_date, '%Y-%m') AS acquisition_month,
        channel,
        COUNT(*)             AS leads,
        SUM(became_customer) AS customers,
        SUM(revenue)         AS revenue
    FROM 
        vw_lead_funnel_summary
    GROUP BY 
        DATE_FORMAT(acquisition_date, '%Y-%m'), 
        channel
),
ranked AS (
    -- Rank channels within each month by revenue
    SELECT 
        *,
        DENSE_RANK() OVER (
            PARTITION BY acquisition_month
            ORDER BY revenue DESC
        ) AS revenue_rank
    FROM 
        monthly_channel
)
SELECT
    acquisition_month,
    channel,
    leads,
    customers,
    ROUND(revenue, 2) AS revenue,
    revenue_rank
FROM 
    ranked
ORDER BY 
    acquisition_month, 
    revenue_rank, 
    channel;


-- ============================================================
-- Q7. Conversion Trend with 3-Month Rolling Average
-- ============================================================
-- Smooths out monthly volatility to show the underlying trend
-- Uses a 3-month moving average for conversion rate
-- ============================================================

SELECT
    acquisition_month,
    lead_to_customer_rate_pct,
    
    -- 3-month rolling average of conversion rate
    -- Includes current month and 2 prior months
    ROUND(
        AVG(lead_to_customer_rate_pct) OVER (
            ORDER BY acquisition_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ), 
        2
    ) AS rolling_3_month_conversion_pct
FROM 
    vw_monthly_acquisition_performance
ORDER BY 
    acquisition_month;
